sudo: required
dist: trusty
language: node_js
node_js:
  - '10.15.0'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm cache verify
- npm run lint
- npm run build:app:prod
- npm run build:lib:prod

script: npm run test:lib
